# Generated by Django 2.2.1 on 2019-06-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRecord',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('coursename', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('pay_flag', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroomid', models.AutoField(primary_key=True, serialize=False)),
                ('classroomname', models.CharField(max_length=20, unique=True)),
                ('note', models.CharField(max_length=50)),
                ('maxpersonnumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classroomorder',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('classroomid', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=20)),
                ('coursename', models.CharField(max_length=20)),
                ('date', models.DateField(default='2019-6-11')),
                ('dateclassnumber', models.IntegerField(default=0)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=20, unique=True)),
                ('trainer', models.CharField(max_length=20)),
                ('courseprice', models.FloatField(default=0.0)),
                ('coursevalid', models.BooleanField(default=True)),
                ('introduction', models.CharField(max_length=100)),
                ('photo', models.ImageField(max_length=30, upload_to='course/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('identity', models.CharField(default='customer', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Customercourseorder',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('classid', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=20)),
                ('valid', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customerinformation',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sex', models.BooleanField(choices=[(True, '女'), (False, '男')], default=True)),
                ('name', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=11)),
                ('birthday', models.DateField(default='1990-01-01')),
                ('profession', models.CharField(default=' ', max_length=20)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('bust', models.FloatField(default=0)),
                ('waistline', models.FloatField(default=0)),
                ('hipline', models.FloatField(default=0)),
                ('shoulderwidth', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.BooleanField(choices=[(True, '女'), (False, '男')], default=True)),
                ('professionaltitle', models.CharField(max_length=30)),
                ('introduction', models.CharField(max_length=100)),
                ('photo', models.ImageField(max_length=30, upload_to='trainer/')),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
